// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// I18NUIClient is the client API for I18NUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type I18NUIClient interface {
	// ListEngineSpecs returns a list of I18N Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (I18NUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type i18NUIClient struct {
	cc grpc.ClientConnInterface
}

func NewI18NUIClient(cc grpc.ClientConnInterface) I18NUIClient {
	return &i18NUIClient{cc}
}

func (c *i18NUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (I18NUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &I18NUI_ServiceDesc.Streams[0], "/v1.I18NUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &i18NUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type I18NUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type i18NUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *i18NUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *i18NUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.I18NUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// I18NUIServer is the server API for I18NUI service.
// All implementations must embed UnimplementedI18NUIServer
// for forward compatibility
type I18NUIServer interface {
	// ListEngineSpecs returns a list of I18N Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, I18NUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedI18NUIServer()
}

// UnimplementedI18NUIServer must be embedded to have forward compatible implementations.
type UnimplementedI18NUIServer struct {
}

func (UnimplementedI18NUIServer) ListEngineSpecs(*ListEngineSpecsRequest, I18NUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedI18NUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedI18NUIServer) mustEmbedUnimplementedI18NUIServer() {}

// UnsafeI18NUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to I18NUIServer will
// result in compilation errors.
type UnsafeI18NUIServer interface {
	mustEmbedUnimplementedI18NUIServer()
}

func RegisterI18NUIServer(s grpc.ServiceRegistrar, srv I18NUIServer) {
	s.RegisterService(&I18NUI_ServiceDesc, srv)
}

func _I18NUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(I18NUIServer).ListEngineSpecs(m, &i18NUIListEngineSpecsServer{stream})
}

type I18NUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type i18NUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *i18NUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _I18NUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(I18NUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.I18NUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(I18NUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// I18NUI_ServiceDesc is the grpc.ServiceDesc for I18NUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var I18NUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.I18NUI",
	HandlerType: (*I18NUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _I18NUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _I18NUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "i18n-ui.proto",
}
